### PR TITLE
feat: add support for Anthropic's Claude 3.5 Sonnet 20241022 edition.

### PR DESCRIPTION
**Pull request by cosmix**
This pull request introduces support for the brand new Anthropic model, `claude-3-5-sonnet-20241022`.

### CODE REVIEW

**Comment by ShivamSphn** [comment]
@cosmix  thanks for adding

**Comment by younes-io** [comment]
+1

@saoudrizwan : Could we please have an ETA for this? It's pretty urgent for those who need to use it. Thanks a lot!

**Comment by ShivamSphn** [comment]
@saoudrizwan aaaa

**Comment by sstehniy** [comment]
guys i'm stupid how do i build and run the fork locally?

**Comment by markushav** [comment]
> guys i'm stupid how do i build and run the fork locally?

You can actually clone this repo, open it with VSCode and ask Cline.

**Comment by markushav** [comment]
> guys i'm stupid how do i build and run the fork locally?

But it was quite easy, just clone the fork and follow the local development instructions: https://github.com/cosmix/cline/tree/main?tab=readme-ov-file#contributing

**Comment by younes-io** [comment]
@cosmix: I don't think this should be closed; it is supposed to be a feature request. I think it should be kept open. Now, whoever wants to fork the repo for every new model out there can do that; nevertheless, I think the feature request should be tracked here. Please let me know.

**Comment by cosmix** [comment]
@younes-io, @saoudrizwan decided to implement the change and support the new Claude 3.5 Sonnet independently, so this PR has no purpose.

**Pull request closed without merging**
