### PR TITLE
Refactor Cline class, improve code organization, and add message deletion feature

### PR DESCRIPTION
**Pull request by yaleh**
## Description
This PR refactors the `Cline` class in `src/core/Cline.ts` to improve code organization, maintainability, and readability. The large monolithic class has been broken down into smaller, more focused components, with many responsibilities delegated to new modules. Additionally, a new feature has been added to allow users to delete individual messages in the chat interface.

# image

## Changes
- Refactored `Cline` class in `src/core/Cline.ts`
- Created new modules:
  - `presentAssistantMessageContent.ts`
  - `clineTypes.ts`
  - `recursivelyMakeClineRequests.ts`
  - `TaskHistoryManager.ts`
- Moved tool execution logic to separate functions
- Improved handling of conversation history and task resumption
- Extracted utility functions to separate files
- Added a new deleteMessage button to each chat message
- Implemented message deletion functionality in the frontend and backend

## New Feature: Message Deletion
- Added a delete button to each message in the chat interface
- Implemented `handleDeleteMessage` function in `ChatView.tsx`
- Added `deleteMessage` case in `ClineProvider.ts`
- Updated `ExtensionStateContext.tsx` to handle message deletion
- Modified `ChatRow.tsx` to include the delete button and handle deletion events

## Testing
- [*] Ensure all existing functionality works as expected
- [*] Test task resumption with various scenarios
- [*] Verify tool execution for all supported tool types
- [*] Test the new message deletion feature:
  - [*] Verify that the delete button appears for each message
  - [*] Confirm that clicking the delete button removes the message from the UI
  - [*] Check that deleted messages are also removed from the backend storage

## Additional Notes
This refactoring is a significant change to the codebase structure. Careful review and thorough testing are required to ensure no functionality has been broken or altered unintentionally. The new message deletion feature should be tested extensively to ensure it works correctly and doesn't introduce any unintended side effects in the conversation flow or history management.

### CODE REVIEW

**Comment by yaleh** [comment]
image

An file list with description was also added to doc/architecture_overview.md. So I can ask Cursor find me the files to work on.

**Comment by ccrvlh** [comment]
That's seems like a great improvement. It would probably make sense to break this down into smaller incremental chunks, though, currently it's very hard to test/review as is.

**Comment by CiberNin** [comment]
The message deletion would be a really great feature. I hope this gets added soon. It's standard in ChatGPT & Claude web apps for a reason.

**Comment by saoudrizwan** [comment]
I apologize for getting to this PR so late, I just moved to a new city and stretched myself a bit too thin this last month. It's too late to merge this in with main, but I appreciate you mentioning the delete idea–I'm working on adding this the extension ASAP.

**Pull request closed without merging**
