### PR TITLE
Create new Settings class

### PR DESCRIPTION
**Pull request by Sarke**
Moved the `alwaysAllowReadOnly` setting to new `Settings` using the standard VS Code settings.

This makes it easier to add more settings in the future, and settings can be on a workspace level.

### CODE REVIEW

**Comment by Sarke** [comment]
Some additions to consider:

1. Link to the settings from the settings panel.
2. Migrate settings from state to VS Code settings.
3. The custom prompts could also be moved, and this would allow per-project (workspace) custom prompts.

**Comment by calebl** [comment]
I like this idea a lot. I was looking through the source to try to figure out how I could set up a different custom prompt per project and I think this solves it in a much more flexible way.

**Comment by ilyaagarkov** [comment]
> Some additions to consider:
> 
> 1. Link to the settings from the settings panel.
> 2. Migrate settings from state to VS Code settings.
> 3. The custom prompts could also be moved, and this would allow per-project (workspace) custom prompts.

Hi @Sarke! Any chance of finishing it?

**Comment by saoudrizwan** [comment]
Thank you for the PR 🙏 Closing since v3 adds a dedicated auto-approve menu, but the new vscode settings idea is great for letting users configure things that done belong in the original settings page.

**Pull request closed without merging**
