### PR TITLE
Multi providers for "OpenAI Compatible"

### PR DESCRIPTION
**Pull request by PhunkyBob**
Feature request: https://github.com/cline/cline/discussions/386

Now, there are 3 entries for "OpenAI Compatible" in the settings:
- OpenAI Compatible
- OpenAI Compatible (alt. 1)
- OpenAI Compatible (alt. 2)

We can now save up to 3 configs of different providers.

### CODE REVIEW

**Comment by nikhil-swamix** [comment]
this.....

the profiles should be backed by a json file, and edit on demand which appear back in UI. 
i have a perfect working lib called DictFile in python, was wondering if python is anyway runnable in vscode...?

**Comment by kneelesh48** [comment]
Instead of 3, just add a button to add as many providers you want and they should be backed by a json or yml file.

**Comment by PhunkyBob** [comment]
> just add a button to add as many providers you want and they should be backed by a json or yml file

I would be glad if you do it and your PR is merged 👍

**Comment by saoudrizwan** [comment]
This would be so useful to people using multiple openai APIs, although I'd like to implement it in a way that allows for unlimited configs, perhaps as a JSON file similar to the MCP settings config. Thank you for the contribution and making this available to people who used your branch

**Pull request closed without merging**
