### PR TITLE
Allow Claude to produce diff files directly when editing

### PR DESCRIPTION
**Pull request by JoziGila**
Claude now responds with only the diff (when editing a file) and applies it, reducing token usage a lot.
The writeToFile is still there but its preferred when creating new files, while applyDiff when editing.

### CODE REVIEW

**Comment by mkearl** [comment]
Would love to see this merged in ASAP

**Comment by saoudrizwan** [comment]
Thanks for the PR! I've tried a very similar solution before but did not have great results for complicated tasks, ie lots of syntax errors or claude would just not make the right changes. I also anticipate anthropic's upcoming fast edit mode will help against lazy coding and give faster results, but until then I'll test this diff approach again and see if I can get it in a mostly good enough state although I'll probaby have users manually opt in to using it.

**Comment by AlexanderHel** [comment]
This is a nice PR since it can work with large file, I just tested it on my project, previously Claude Dev can't handle my gui file which is over 500 lines which result to multiply retrying error messages, but with this PR it can work on that file.

But as saoudrizwan sad, it will make lots of syntax errors, which need some fixing.

**Comment by marksolly** [comment]
> But as saoudrizwan sad, it will make lots of syntax errors, which need some fixing.

@AlexanderHel  What type of syntax errors have you been seeing? I use this approach with GPT4o and find it's excellent for reducing output size and the code quality seems fine. Still experimenting with Claude Sonnet.

**Comment by saoudrizwan** [comment]
Adding `"(diff -u)"` was a good idea, I got claude to consistently output valid diffs this way (only had ~70% success rate without it) but still running into some problems I've ran into before with structured outputs. It cant do basic tasks–cursor talks about this in a blog post but basically its trained on way less patch diffs than entire code files so it just *sucks* at writing code through diffs. I couldnt even get it to make a snake game on the first try... I then tried giving it the option of using full contents OR diff format, and it almost always chose full contents no matter how small the changes were.

I suspect adding in a diff format is gonna lead to pretty bad results for a lot of people that rely on claude dev so I'm hesitant to add it until I at least get the chance to try anthropic's fast edit mode.

**Comment by JoziGila** [comment]
An interesting problem for sure, Im still thinking on how yo improve this. https://aider.chat/docs/leaderboards/#notes-on-benchmarking-results

**Comment by CiberNin** [comment]
Imo the key to prompt with sufficiently neutral language that Claude is not biased to prefer diffs or full page replacements. Giving it options more that restrictions.

**Comment by MaciejMogilany** [comment]
Please reconsider implementing this. Maybe as an option. Every single response from ClaudDev is followed by mine "do not truncate print full code try gain" Double tokens generation, double time to wait. I always see that diff are pasted in correct places in vscode. Sonet truncate responses above 200 lines of code. This become frustrating to use.

**Comment by saoudrizwan** [comment]
I made a wiki doc about working around the `//rest of code` issue here: https://github.com/saoudrizwan/claude-dev/wiki/Troubleshooting-%E2%80%90-Claude-Deleting-Code-with-%22rest-of-code-here%22-Comments

**Comment by marksolly** [comment]
Fantastic effort Saoud Rizwan. Thank you.

**Comment by pietz** [comment]
With the new Sonnet 3.5 version out, I wanted to revisit the topic.

Anthropic introduced a lot, but quick code edit is not one of them. Also, based on the same logic of having function calling work the same for all the models out there, this might be a better approach that works for all providers.

Aider Chat [uses diff mode](https://aider.chat/docs/leaderboards/) for all of the top models on the leaderboard. They also provide some [details about how their diff works](https://aider.chat/docs/more/edit-formats.html#diff).

I would really like to see this. Around 90% of the code Cline generates is just copy and paste. It costs a lot of tokens and takes a lot of time. At least having the option for diff mode would be highly appreciated.

**Comment by aviramkofman** [comment]
This is one of the required features for me due to cost reduction and speed. 

Love cline but this is really missing

Please merge 🙏

**Comment by ccrvlh** [comment]
The full file rewrite ended up being a deal breaker for me: constantly deleting working code, super expensive, constantly hitting anthropic API rate limits. Got an alternative but similar working approach here: https://github.com/ccrvlh/cline/commit/c4b90017bb317144db1aa95c09893f3d5c79407a with a `SearchAndReplace` tool and a `InsertCodeBlock` tool - been using it for a few days now, great experience. @saoudrizwan happy to open a PR if you feel this makes sense for the project.

**Comment by dikkietrom** [comment]
this is not the way, i asked it to make a custom diff tool that works much better than trying to generate valid git diffs. for me without partial updates it is pretty much useless, slow and expensive. I am still working on it but here is the code. it is not a claude tool, i have my own tool format but you can easily convert it into an officia claude tool.
[custom diff tool.zip](https://github.com/user-attachments/files/17673043/custom.diff.tool.zip)

**Comment by saoudrizwan** [comment]
Hey folks! I recently updated Cline with diff editing where it uses a flexible search/replace format that ignores whitespace mismatches, and falls back to whole file editing for complex edits. Please try it out and let me know how it works!

**Comment by dikkietrom** [comment]
> Hey folks! I recently updated Cline with diff editing where it uses a flexible search/replace format that ignores whitespace mismatches, and falls back to whole file editing for complex edits. Please try it out and let me know how it works!

funny I did notice it works faster first and then discovered it is working with diffs now, great and thanks!

**Comment by marksolly** [comment]
This seems to be working quite well for me. I have not struck any file size
limitations since installing this version and edits are fast.

**Comment by dikkietrom** [comment]
> Hey folks! I recently updated Cline with diff editing where it uses a flexible search/replace format that ignores whitespace mismatches, and falls back to whole file editing for complex edits. Please try it out and let me know how it works!

suggestion to speed the actual editing up, still small changes in very large files is extremely slow , which i did not understand so i asked 
image

**Pull request closed without merging**
