### PR TITLE
Fix: Enable HTTP proxy support for AnthropicBedrock client

### PR DESCRIPTION
**Pull request by bamps53**
This change addresses an issue where the AnthropicBedrock client did not automatically handle HTTP proxies, which could lead to connectivity problems for users behind corporate firewalls or using proxy servers.
The solution explicitly passes the HTTPS_PROXY or HTTP_PROXY environment variable to the client's httpAgent configuration, ensuring that proxy settings are respected.

### CODE REVIEW

**Comment by saoudrizwan** [comment]
I don't think this belongs in the main extension–I believe you can accomplish the same effect using third party software. Thank you for the PR though, and making this available to anyone that used your branch.

**Comment by n-r-w** [comment]
@bamps53 I suggest doing a similar pr in https://github.com/RooVetGit/Roo-Cline. Perhaps its author will be more interested in proxy support.

**Comment by tedyyu** [comment]
Isn't it the same root cause for the [openrouter model retrieval issue](https://github.com/cline/cline/issues/892)? Why not consider such a fix for all providers?

**Comment by ZeroCool2u** [comment]
I don't understand, why was this closed? It is making it impossible to use Cline in certain corporate environments.

**Pull request closed without merging**
