### PR TITLE
SAP AI Core as a Provider

### PR DESCRIPTION
**Pull request by schardosin**
This PR adds SAP AI Core as one of the providers for Claude Dev, it will look to the existing deployments in a SAP AI Core instance, and looking for a match for the models Claude 3.5 Sonnet or Claude 3 Sonnet, depending on the user selection.

SAP AI Core is a service in the SAP Business Technology Platform that is designed to handle the execution and operations of your AI assets in a standardized, scalable, and hyperscaler-agnostic way. It provides seamless integration with your SAP solutions. Any AI function can be easily realized using open-source frameworks. SAP AI Core supports full lifecycle management of AI scenarios. Access generative AI capabilities and prompt lifecycle management via the generative AI hub.

SAP AI Core allows you to experiment with and utilize natural language prompts with a variety of generative AI models in the generative AI hub.

### CODE REVIEW

**Comment by schardosin** [comment]
Hi @saoudrizwan 

I've been using this fork for almost a month now, and it works great! It's another option for Claude-Dev, and I’ve kept it updated with the latest upstream changes, resolving all conflicts along the way.

It would be ideal to have this merged if there's interest in including it as part of the project. Let me know if there's anything else you'd like me to address.

Thank you!

**Comment by saoudrizwan** [comment]
Sorry @schardosin I don't want to add any APIs to Cline that I'm not too familiar with. You are free to use open ai compatible otherwise

**Comment by ncryptedV1** [comment]
~~@saoudrizwan SAP AI Core enables the use of Cline in environments with business-critical data that cannot be used with usual inference providers → unlocks a completely new user base. [The fork](https://github.com/schardosin/cline-sap-ai-core/) is still kept up-to-date and is in active use internally. A reconsideration would be heavily appreciated.~~

**Comment by schardosin** [comment]
@ncryptedV1 We have a new PR review in progress for this:
https://github.com/cline/cline/pull/3980

**Pull request closed without merging**
