### PR TITLE
Make change "at cursor" (@cursor) or "within selection" (@selection)

### PR DESCRIPTION
**Pull request by PhunkyBob**
Feature request: https://github.com/cline/cline/discussions/473

# Feature
This PR add 2 new keywords to use in the prompt:
- `@cursor`: when used, the code generated by the prompt should be added at the cursor current position in the current file opened in editor.
- `@selection`: when used, the code generated by the prompt should replace the code in current selection in the current file opened in editor.
In both cases, the rest of the file should not be modified.

# Exemples
## `@cursor`
```
@cursor add a new paragraph that says "hello"
```
This should create a new paragraph exactly at the cursor position .

## `@selection`
Select a whole function in the current file
```
@position add a parameter "max_items" and limit the behavior of the function regarding.
```
This update only the selected function with a new parameter "max_item" and change the code accordingly.

# Additional info
When `@selection` is used and there is no selection in the code, fall back to `@cursor`.

### CODE REVIEW

**Comment by saoudrizwan** [comment]
Hi @PhunkyBob thank you for taking the time to open this PR, I'm impressed you got something like this to work! I'm avoiding adding too many options to the context mention menu, and I think this feature may not be as useful anymore now that Cline v3 does diff editing for targeted edits. You can now just ask him to replace a line or section instead. Apologies for getting back so late, I moved to a new city and was stretched a bit think this last month.

**Comment by songqiang** [comment]
I also feel this feature will be useful. It is a more intuitive experience to select and tell what to do. Similar feature is requested in https://github.com/cline/cline/discussions/492

**Comment by Almenon** [comment]
Copilot lets you run AI against a selection, it would be nice if Cline had this functionality as well. It's one of the first things I looked for.

**Comment by songqiang** [comment]
In case anyone not aware of: Cline now has a new "Add to Cline" option when you right click a selected code snippets, which does the thing we want: https://cline.bot/blog/cline-3-8-0-workflow-integration-account-management-and-provider-optimization#:~:text=New%20Integration%20Points-,Add%20to%20Cline,-Adding%20context%20to

**Pull request closed without merging**
