### PR TITLE
Auto-merger, Terminal upgrade, Debug console usage++

### PR DESCRIPTION
**Pull request by asbis**
This PR includes several upgrades i have been working on and been using for the last 3-4 weeks.

1. Automerger:
Now the extension are using search and replace commands for editing. When the files gets too big, editing gets to complicated and time consuming. Instead the extension will ask to search up exactly the code it wants to edit and replace it with the new code. Looks like this:
```
<<<<<<< SEARCH
  "theme": "light",
=======
  "theme": "dark",
>>>>>>> REPLACE

```
If it sometimes forgets it, just remind it to use search and replace commands while editing, and it will use it.

2. Auto accept:
Now you can easly turn on and off auto accept straight from the chat view. Sometimes, when it is doing repetive coding, it is nice to turn it on. With the search and replace command it is much safer to leave this on. 

Skjermbilde 2024-12-13 kl  09 56 44

3. Added sounds
I found another PR that added sounds. This is great when you are using auto accept to get feedback when it is ready, so you can focus on other stuff. This can be turned off and on from settings.

4. Read the Debug console
If you run you project from vscode launcher, it will now feed the debug console to the ai. This is super great when you are running a backend server and you dont pay attention to errors that happens in the backend. It will automatically pick that up and fix it right away when it gets an 500/404 or anything.

### CODE REVIEW

**Comment by rekdt** [comment]
I don't think the find and replace works. It can add code, but it can't remove it. As a test below i asked it to remove a comment and it couldn't. 

image

**Comment by asbis** [comment]
Which model did you use? Sometimes it does have issue to find it, but just specify it to try again and ask it to write the exact same code.

Works great with sonnet 3.5

**Comment by rekdt** [comment]
I am using the new Sonnet 3.5 model. Does your find and replace show a diff of "-" when replacing that part of the code?  Would love to see a screenshot of what the diff looks like when you ask it to replace something. I see your search and replace in the PR. The logs don't say much, other than reverting the file. No reason for failure is given.

**Comment by asbis** [comment]
The view you see:

```
+ 
+
+
-
-
-
```
Is just added into the chatview, for you to see what the differences. These are not provided by the ai.


Based on the screenshot you provided it should remove the what you asked for.
In your code, was it not removed?

Here is how it looks for me when i ask it to remove apple pay, google pay, klarna and paypal as payment methods:

Skjermbilde 2024-12-16 kl  10 16 22

**Comment by saoudrizwan** [comment]
Hi @asbis appreciate the PR! I am sure you are aware that most of these changes were added in v3. Thank you for taking a stab at the diff edit implementation. Since you've had some experience playing around with it, can you try out the diff editing in v3 and see how it works for you? I'd love to hear your experience and any ideas you might have for improving the [diff parsing](https://github.com/cline/cline/blob/main/src/core/assistant-message/diff.ts).

**Comment by d121122gma** [comment]
‫أُرسلت من الـ iPhone‬‫في ٢٢‏/١٢‏/٢٠٢٤ الساعة ٦:١٦ ص، كتب/كتبت ‏Saoud Rizwan ***@***.***>:‬﻿
Closed #901.

**Pull request closed without merging**
