### PR TITLE
Added search_google and fetch_webpage_content tools for internet access

### PR DESCRIPTION
**Pull request by AnsonLai**
Added two new tools to give the agent internet access.  This gives the tool some ability to access online documentation.  I can drop a link directly or ask it to search Google.  Google Custom Search requires an API key and ID.

**`search_google`**: Perform a Google Custom Search using the specified query. This tool allows gathering information from Google search results based on user input. The search results will be formatted and displayed to the user, enabling further actions or decisions based on the findings.
**`fetch_webpage_content`**: Fetch the HTML content of a webpage from a specified URL. This tool retrieves the webpage's contents and presents it to the user for further actions or analysis.

### CODE REVIEW

**Comment by saoudrizwan** [comment]
Incredible! Will look into this asap, thank you for the PR!

**Comment by eddiefleurent** [comment]
very cool! thanks for the contribution. 
I have been using Perplexity a lot as it does the searching + LLM parsing in 1 call. I'm actually manually taking the output of Claude Dev and feeding to Perplexity back and forth to help it when it gets stuck due to outdated training data or docs. 
I'm going to draw on how you implemented google and see if I can add a Perplexity tool to it soon

**Comment by eddiefleurent** [comment]
> very cool! thanks for the contribution. I have been using Perplexity a lot as it does the searching + LLM parsing in 1 call. I'm actually manually taking the output of Claude Dev and feeding to Perplexity back and forth to help it when it gets stuck due to outdated training data or docs. I'm going to draw on how you implemented google and see if I can add a Perplexity tool to it soon

well now with Cline able to call all of OpenRouter, you can query any of the Perplexity online models which does the searching, parsing, and LLM output in one call :) guess neither search or Perplexity implementation is no longer needed.

**Comment by namnx228** [comment]
> > very cool! thanks for the contribution. I have been using Perplexity a lot as it does the searching + LLM parsing in 1 call. I'm actually manually taking the output of Claude Dev and feeding to Perplexity back and forth to help it when it gets stuck due to outdated training data or docs. I'm going to draw on how you implemented google and see if I can add a Perplexity tool to it soon
> 
> well now with Cline able to call all of OpenRouter, you can query any of the Perplexity online models which does the searching, parsing, and LLM output in one call :) guess neither search or Perplexity implementation is no longer needed.

I think this search feature is still an invaluable feature as Perplexity doesn't have "computer use" capability that Claude has.

**Comment by saoudrizwan** [comment]
Wanted to circle back to this PR and let everyone here know that you can now add these tools using [MCP](https://x.com/sdrzn/status/1867271665086074969)!

**Pull request closed without merging**
