### PR TITLE
All Gemini-2.0-Flash models will all have computer usage enabled and Openrouter API Features Added

### PR DESCRIPTION
**Pull request by viasky657**
I had trouble with a stable Openrouter connection using the newest release of Cline which may be due to the API provider or other connectivity issues. I tried using Roo Cline's implementation of Openrouter and it worked more consistently. I updated Cline to use Roo's implementation of Openrouter so it may be more stable more consistently. I have not tried the diff editable usage with this API provider yet so it may have some difficulties with diff implementation. I will update this once I have tried using the diff with Cline some more.

### CODE REVIEW

**Comment by viasky657** [comment]
Update. I have tried using Cline for a while with this addon and it seems to be working fine in the Github Codespace with the Openrouter API after these changes. Please let me know if there are any bugs I may have missed and I will gladly fix them. Thank you for your time.

**Comment by viasky657** [comment]
I added more features such as computer usage with Google Gemini 2.0 Flash and Gemini 2.0 Flash Thinking (experimental) models for both Openrouter and Gemini api usage. The webview has a bug that I am currently working on so for Openrouter only, the Gemini 2.0 models will say that it doesn't have computer usage enable on the UI, but it will be still working as normal on the backend. I am currently working on fixing this UI error.

**Comment by saoudrizwan** [comment]
Hey Viasky! There is no difference beween the roo implementation of the openrouter API handler and cline's. 

Regarding the browser action tool for gemini, the tools are defined in the system prompt and not as part of the tools parameter for the API requests. 

If I'm missing something or if you have any questions, please let me know.

**Comment by viasky657** [comment]
Thank you for letting me know. I appreciate the feedback.

**Pull request closed without merging**
