### PR TITLE
adding new gemini model"gemini-exp-1114" support

### PR DESCRIPTION
**Pull request by RogelioRichmanAstronaut**
has 32767 of context and 8192 of output

### CODE REVIEW

**Comment by gregorypatton** [comment]
Has this been implemented fully yet?
Any time I try to configure Cline to use google/gemini-exp-1114 it returns an error `Provider returned error`
Not seeing any debug output

**Comment by RogelioRichmanAstronaut** [comment]
Screenshot 2024-11-17 at 13 42 src=
@gregorypatton check if you already have access to the model on Google Ai Studio https://aistudio.google.com/.

**Comment by Steake** [comment]
I used it the day of release with my api key, now its vanished from the list...

**Comment by 3C0D** [comment]
if it can help someone
image

**Comment by 3C0D** [comment]
API Provider
OpenAl Compatible
Base URL
https://generativelanguage.googleapis.com/v1beta
API Key
Model ID
gemini-exp-1114

**Comment by WannabDad** [comment]
Does this also appear to you guys like this?
image

**Comment by MoZyo** [comment]
Experimental 1121 already out too.

**Comment by saoudrizwan** [comment]
I apologize for not getting to this PR sooner, I just finished moving to a new city and was stretched a bit thin this last month. I'll be better about PRs especially with model updates–I'm not always in the loop about the newest model so these contributions are appreciated.

**Pull request closed without merging**
